<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>sii</string>
		<string>mat</string>
	</array>
	<key>name</key>
	<string>SCS Software</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#object-name</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>:</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.separator.dictionary.key-value.sii</string>
				</dict>
			</dict>
			<key>end</key>
			<string>$|(?=\})</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>comment</key>
					<string>the SII object value</string>
					<key>include</key>
					<string>#value</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#comments</string>
				</dict>
				<dict>
					<key>match</key>
					<string>[^\s]</string>
					<key>name</key>
					<string>invalid.illegal.expected-dictionary-separator.json</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>include</key>
			<string>#object</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#comments</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>array</key>
		<dict>
			<key>begin</key>
			<string>\(</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.array.begin.sii</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\)</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.array.end.sii</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.structure.array.sii</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#value</string>
				</dict>
				<dict>
					<key>match</key>
					<string>,</string>
					<key>name</key>
					<string>punctuation.separator.array.sii</string>
				</dict>
				<dict>
					<key>match</key>
					<string>[^\s\)]</string>
					<key>name</key>
					<string>invalid.illegal.expected-array-separator.sii</string>
				</dict>
			</array>
		</dict>
		<key>comments</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>/\*\*</string>
					<key>captures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.comment.sii</string>
						</dict>
					</dict>
					<key>end</key>
					<string>\*/</string>
					<key>name</key>
					<string>comment.block.documentation.sii</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>/\*</string>
					<key>captures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.comment.sii</string>
						</dict>
					</dict>
					<key>end</key>
					<string>\*/</string>
					<key>name</key>
					<string>comment.block.sii</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\s*(#).*$\r?\n?</string>
					<key>name</key>
					<string>comment.line.number-sign.sii</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\s*(//).*$\r?\n?</string>
					<key>name</key>
					<string>comment.line.double-slash.sii</string>
				</dict>
			</array>
		</dict>
		<key>constant</key>
		<dict>
			<key>match</key>
			<string>\b(?:true|false|null|nil)\b</string>
			<key>name</key>
			<string>constant.language.sii</string>
		</dict>
		<key>hexadecimal</key>
		<dict>
			<key>comment</key>
			<string>handles hexadecimal numbers</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>&amp;\b[0-9A-Fa-f]+\b</string>
					<key>name</key>
					<string>storage.type.sii</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(0(x|X))?[0-9A-Fa-f]+\b</string>
					<key>name</key>
					<string>constant.numeric.hexadecimal.sii</string>
				</dict>
			</array>
		</dict>
		<key>include</key>
		<dict>
			<key>begin</key>
			<string>\s*((@)include\b)\s*</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.at-rule.include.sii</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.keyword.sii</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\s*(?=$)</string>
			<key>name</key>
			<string>meta.at-rule.include.sii</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#string-quoted</string>
				</dict>
			</array>
		</dict>
		<key>numeric</key>
		<dict>
			<key>comment</key>
			<string>handles numeric numbers</string>
			<key>match</key>
			<string>[+-]?\d+([.]\d+)?[fF]?\b</string>
			<key>name</key>
			<string>constant.numeric.sii</string>
		</dict>
		<key>object</key>
		<dict>
			<key>begin</key>
			<string>\{</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.dictionary.begin.sii</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>a SII object</string>
			<key>end</key>
			<string>\}</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.dictionary.end.sii</string>
				</dict>
			</dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#include</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#object-name</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#comments</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>:</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.separator.dictionary.key-value.sii</string>
						</dict>
					</dict>
					<key>end</key>
					<string>$|(?=\})</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>comment</key>
							<string>the SII object value</string>
							<key>include</key>
							<string>#value</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#comments</string>
						</dict>
						<dict>
							<key>match</key>
							<string>[^\s]</string>
							<key>name</key>
							<string>invalid.illegal.expected-dictionary-separator.json</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>include</key>
					<string>#object</string>
				</dict>
				<dict>
					<key>match</key>
					<string>[^\s\}]</string>
					<key>name</key>
					<string>invalid.illegal.expected-dictionary-separator.sii</string>
				</dict>
			</array>
		</dict>
		<key>object-name</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.sii</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.parameters.sii</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.sii</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.parameters.sii</string>
				</dict>
				<key>5</key>
				<dict>
					<key>name</key>
					<string>constant.numeric.sii</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>the SII object key</string>
			<key>match</key>
			<string>(ui)?(::)?([\w_]+)(\[(\d*)\])?</string>
		</dict>
		<key>string-quoted</key>
		<dict>
			<key>begin</key>
			<string>"</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.begin.sii</string>
				</dict>
			</dict>
			<key>end</key>
			<string>"</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.end.sii</string>
				</dict>
			</dict>
			<key>name</key>
			<string>string.quoted.double.sii</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>(?x:                # turn on extended mode
                     \\                # a literal backslash
                     (?:               # ...followed by...
                       ["\\/bfnrt]     # one of these characters
                       |               # ...or...
                       u               # a u
                       [0-9a-fA-F]{4}  # and four hex digits
                     )
                   )</string>
					<key>name</key>
					<string>constant.character.escape.sii</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\\.</string>
					<key>name</key>
					<string>invalid.illegal.unrecognized-string-escape.sii</string>
				</dict>
			</array>
		</dict>
		<key>string-unquoted</key>
		<dict>
			<key>begin</key>
			<string>\w</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.begin.sii</string>
				</dict>
			</dict>
			<key>end</key>
			<string>$|(?=(\{|#|//))</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.end.sii</string>
				</dict>
			</dict>
			<key>name</key>
			<string>string.unquoted.double.sii</string>
		</dict>
		<key>string-unquoted-dot</key>
		<dict>
			<key>begin</key>
			<string>(\.)?([_A-Za-z][\w_]+)(\[(\d*)\])?(\.)|(\.)([_A-Za-z][\w_]+)(\[(\d*)\])?</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.begin.sii</string>
				</dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.parameters.sii</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>storage.modifier.sii</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.parameters.sii</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>constant.numeric.sii</string>
				</dict>
				<key>5</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.parameters.sii</string>
				</dict>
				<key>6</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.parameters.sii</string>
				</dict>
				<key>7</key>
				<dict>
					<key>name</key>
					<string>storage.modifier.sii</string>
				</dict>
				<key>8</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.parameters.sii</string>
				</dict>
				<key>9</key>
				<dict>
					<key>name</key>
					<string>constant.numeric.sii</string>
				</dict>
			</dict>
			<key>end</key>
			<string>$|(?=(\{|#|//))</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.end.sii</string>
				</dict>
			</dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\.</string>
					<key>name</key>
					<string>punctuation.definition.parameters.sii</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>storage.modifier.sii</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.parameters.sii</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>constant.numeric.sii</string>
						</dict>
					</dict>
					<key>match</key>
					<string>([\w_]+)(\[(\d*)\])?</string>
				</dict>
			</array>
		</dict>
		<key>value</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#constant</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#string-quoted</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#array</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#numeric</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#string-unquoted-dot</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#hexadecimal</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#string-unquoted</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#comments</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#object</string>
				</dict>
			</array>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.sii</string>
	<key>uuid</key>
	<string>bc4a5bb8-2153-45b6-b195-b318324c3d3b</string>
</dict>
</plist>
